"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { BlogData, EditorData } from "@/types/content";
import { slugify } from "@/lib/site";
import { Editor } from "@/components/admin/Editor";
const blankContent:EditorData={blocks:[]};
const empty={title:"",slug:"",excerpt:"",coverImage:"",coverImageAlt:"",socialImage:"",content:blankContent,contentFormat:"editorjs",tags:[],seoTitle:"",metaDescription:"",seoKeywords:[],canonicalUrl:"",featured:false,status:"draft"} as unknown as BlogData;
const csv=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);
export function BlogForm({initial}:{initial?:BlogData}){const router=useRouter();const legacy=initial&&typeof initial.content==="string";const [data,setData]=useState<BlogData>(initial?{...initial,content:legacy?blankContent:initial.content,contentFormat:"editorjs"}:empty);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const set=(key:keyof BlogData,value:unknown)=>setData(prev=>({...prev,[key]:value}));
 async function save(status:"draft"|"published"){setBusy(true);setMessage("");const payload={...data,status};const response=await fetch(initial?`/api/blogs/${initial._id}`:"/api/blogs",{method:initial?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(result.error||"Could not save article.");return;}router.push("/dashboard/blogs");router.refresh();}
 return <div className="dashboard-form"><div className="editor-layout"><div className="form-stack"><section className="form-card"><h2>Article</h2>{legacy?<p className="warning">This article uses legacy content. Its public page remains readable. Saving here converts it to Editor.js; copy the legacy text first if you still need it.</p>:null}<label>Title<input required value={data.title} onChange={e=>{set("title",e.target.value);if(!initial)set("slug",slugify(e.target.value));}}/></label><label>Slug<input required value={data.slug} onChange={e=>set("slug",slugify(e.target.value))}/></label><label>Excerpt <small>{data.excerpt.length}/360</small><textarea required minLength={10} maxLength={360} rows={4} value={data.excerpt} onChange={e=>set("excerpt",e.target.value)}/></label><label>Cover image URL<input type="url" value={data.coverImage||""} onChange={e=>set("coverImage",e.target.value)}/></label><label>Cover alt text<input value={data.coverImageAlt||""} onChange={e=>set("coverImageAlt",e.target.value)}/></label></section><section className="form-card editor-card"><h2>Content</h2><Editor value={data.content as EditorData} onChange={value=>set("content",value)}/></section></div><aside className="form-stack"><section className="form-card"><h2>Publishing</h2><p className="status-label">Current status: <strong>{data.status}</strong></p><label className="check"><input type="checkbox" checked={data.featured} onChange={e=>set("featured",e.target.checked)}/> Featured article</label><div className="button-stack"><button className="button secondary" disabled={busy} onClick={()=>save("draft")}>{busy?"Saving…":"Save draft"}</button><button className="button" disabled={busy} onClick={()=>save("published")}>{busy?"Saving…":"Publish"}</button></div>{initial?.status==="published"?<button className="dash-link" disabled={busy} onClick={()=>save("draft")}>Unpublish</button>:null}</section><section className="form-card"><h2>Taxonomy & SEO</h2><label>Tags — comma separated<input value={data.tags.join(", ")} onChange={e=>set("tags",csv(e.target.value))}/></label><label>SEO title <small>{(data.seoTitle||"").length}/70</small><input maxLength={70} value={data.seoTitle||""} onChange={e=>set("seoTitle",e.target.value)}/></label><label>Meta description <small>{(data.metaDescription||"").length}/170</small><textarea maxLength={170} value={data.metaDescription||""} onChange={e=>set("metaDescription",e.target.value)}/></label><label>SEO keywords<input value={data.seoKeywords.join(", ")} onChange={e=>set("seoKeywords",csv(e.target.value))}/></label><label>Canonical URL<input type="url" value={data.canonicalUrl||""} onChange={e=>set("canonicalUrl",e.target.value)}/></label><label>Social image URL<input type="url" value={data.socialImage||""} onChange={e=>set("socialImage",e.target.value)}/></label></section>{message?<p className="form-error" role="alert">{message}</p>:null}</aside></div></div>;
}
