"use client";
import { useEffect, useId, useRef } from "react";
import type { EditorData } from "@/types/content";
export function Editor({ value, onChange }: { value: EditorData; onChange:(data:EditorData)=>void }) {
  const id=useId().replace(/:/g,""); const editor=useRef<{destroy:()=>void;save:()=>Promise<EditorData>} | null>(null); const initialValue=useRef(value); const changeHandler=useRef(onChange);
  useEffect(()=>{changeHandler.current=onChange},[onChange]);
  useEffect(()=>{ let active=true; (async()=>{ const [{default:EditorJS},{default:Header},{default:List},{default:Quote},{default:Code},{default:Delimiter},{default:Table},{default:Checklist},{default:InlineCode},{default:Marker},{default:ImageTool},{default:Embed}] = await Promise.all([import("@editorjs/editorjs"),import("@editorjs/header"),import("@editorjs/list"),import("@editorjs/quote"),import("@editorjs/code"),import("@editorjs/delimiter"),import("@editorjs/table"),import("@editorjs/checklist"),import("@editorjs/inline-code"),import("@editorjs/marker"),import("@editorjs/image"),import("@editorjs/embed")]); if(!active)return; const instance=new EditorJS({holder:id,data:initialValue.current,placeholder:"Start writing…",minHeight:420,tools:{header:Header,list:List,quote:Quote,code:Code,delimiter:Delimiter,table:Table,checklist:Checklist,inlineCode:InlineCode,marker:Marker,image:{class:ImageTool,config:{uploader:{uploadByUrl:async(url:string)=>({success:1,file:{url}}),uploadByFile:async()=>({success:0,file:{url:""}})}}},embed:{class:Embed,config:{services:{youtube:true}}}},onChange:async()=>changeHandler.current(await instance.save() as EditorData)}); editor.current=instance as unknown as typeof editor.current; })(); return()=>{active=false; editor.current?.destroy();editor.current=null;}; },[id]);
  return <div className="editor-shell"><div id={id}/><p className="field-help">Use the + toolbar for headings, lists, code, tables, URL-based images, and YouTube embeds. File upload is intentionally disabled until a media provider is configured.</p></div>;
}
