import dotenv from "dotenv";
import { connectToDatabase } from "../lib/db";
import { Project } from "../models/Project";
dotenv.config({ path: ".env.local" });
dotenv.config();
const projects=[
{title:"Lupofy",slug:"lupofy",type:"AI-powered smart link management and branded URL shortener SaaS",company:"NexiBy LLC",role:"Full Stack Developer",ownership:"company",status:"live",summary:"An AI-powered SaaS for branded links, custom domains, subscription plans, and link intelligence—built for NexiBy LLC.",description:"I built Lupofy as a full-stack SaaS product for NexiBy LLC. The system combines branded link management, custom domains, subscription controls, analytics, a fast redirect engine, and AI-assisted metadata workflows.",coverImage:"https://nexiby.com/wp-content/uploads/2026/05/Dribbble-Shot-lupofy-scaled.png",coverImageAlt:"Lupofy link management dashboard",liveUrl:"https://lupofy.com",technologies:["Next.js","React","Node.js","PostgreSQL","Stripe","OpenAI","Tailwind CSS"],highlights:["Custom slugs, branded links, and custom domain support","Stripe subscriptions and link quota enforcement","AI metadata extraction, title and description generation, preview imagery, and slug suggestions","Analytics tracking and a scalable redirect foundation"],responsibilities:["Full-stack SaaS development","Responsive product dashboard","Link management and analytics workflows","Backend architecture for redirects and intelligent link features"],featured:true,published:true,sortOrder:1},
{title:"Dokaneasy",slug:"dokaneasy",type:"Multi-tenant eCommerce SaaS",role:"Founder / Full Stack Developer",ownership:"personal",status:"development",summary:"My own multi-tenant commerce SaaS, designed so each business operates in an isolated workspace with its own storefront, domain, products, orders, and settings.",description:"Dokaneasy is my founder product: a scalable multi-tenant eCommerce platform with isolated business workspaces, custom domains, theme-based storefronts, subscription controls, and tenant dashboards.",liveUrl:"https://dokaneasy.com",technologies:["Next.js","Node.js","PostgreSQL","Prisma","Nginx"],highlights:["Tenant isolation and dynamic tenant routing","Custom domains through Nginx reverse proxy","Theme-based customizable storefront system","Products, inventory, orders, customers, analytics, subscriptions, and RBAC"],responsibilities:["Product architecture and founder-led development","Multi-tenant data and routing design","Storefront and dashboard systems"],featured:true,published:true,sortOrder:2},
{title:"FabtrixBD",slug:"fabtrixbd",type:"E-commerce platform",role:"Full Stack Developer",ownership:"client",status:"live",summary:"A responsive commerce platform covering customer shopping flows and the operational tools behind products, orders, inventory, pricing, and access control.",description:"FabtrixBD combines a React storefront with Laravel backend APIs and administration workflows for running an e-commerce operation.",liveUrl:"https://fabtrixbd.com",technologies:["Laravel","React.js","MySQL"],highlights:["Product browsing, cart, and checkout","Order, product, category, customer, inventory, and pricing management","Authentication and role-based access","Responsive React interface backed by Laravel APIs"],responsibilities:["Frontend and backend implementation","Commerce workflow development","Administration and access-control features"],featured:true,published:true,sortOrder:3},
{title:"Webwatchly",slug:"webwatchly",type:"AI-driven SEO change monitoring SaaS",company:"NexiBy LLC",role:"Full Stack Developer",ownership:"company",status:"live",summary:"An AI-driven monitoring product that detects meaningful SEO changes, explains them, and connects site history with search performance.",description:"Webwatchly monitors titles, canonicals, robots directives, and schema, then uses AI to explain differences and their likely importance. It combines daily monitoring with Google Search Console data, alerts, workspaces, subscriptions, and history retention.",liveUrl:"https://webwatchly.com",technologies:["Next.js","React","Node.js","PostgreSQL","OpenAI","Google Search Console API","Stripe"],highlights:["AI explanation and severity classification","Before-and-after SEO change tracking","Google Search Console integration and performance correlation","Email and in-app alerts, workspaces, subscriptions, and history"],responsibilities:["AI workflow implementation","Monitoring and difference-tracking systems","SaaS dashboard and subscription features"],featured:true,published:true,sortOrder:4},
{title:"Kbixy",slug:"kbixy",type:"AI-powered knowledge base SaaS",company:"NexiBy LLC",role:"Full Stack Developer",ownership:"company",status:"live",summary:"A multi-tenant knowledge platform with AI-assisted writing, semantic discovery, contextual chat, and searchable video knowledge.",description:"Kbixy combines branded tenant knowledge bases with a Notion-style editor, AI article tools, semantic search, contextual assistance, video recording and transcription, subscriptions, credits, and team access.",coverImage:"https://kbixy.com/assets/images/dashboard.png",coverImageAlt:"Kbixy knowledge base dashboard",liveUrl:"https://kbixy.com",technologies:["Next.js","Node.js","PostgreSQL","OpenAI","LangChain","Whisper","Stripe","Typesense"],highlights:["AI drafting, tagging, summarization, semantic search, and contextual chat","Browser screen and camera recording with Whisper transcription","Branded subdomains, tenant isolation, teams, and RBAC","Subscriptions, AI credits, version control, and rich-text authoring"],responsibilities:["Multi-tenant SaaS development","AI and search workflows","Knowledge editing and video systems"],featured:true,published:true,sortOrder:5},
{title:"LeaseLocals",slug:"leaselocals",type:"Marketplace subscription SaaS for car leasing",role:"Full Stack Developer",ownership:"company",status:"live",summary:"A subscription marketplace serving customer, dealer, and admin workflows around vehicle lease listings and discovery.",description:"LeaseLocals supports listing creation and publishing, marketplace search and filtering, account dashboards, plan-based access, recurring payments, and the APIs connecting customer, dealer, and admin experiences.",liveUrl:"https://leaselocals.com",technologies:["Next.js","Node.js","PostgreSQL","Stripe"],highlights:["Customer, dealer, and admin workflows","Lease listing management, publishing, discovery, and filtering","Stripe plans, access controls, and recurring payments","Marketplace APIs, dashboards, and account management"],responsibilities:["Full-stack marketplace development","Subscription and plan-access workflows","Listing and discovery systems"],featured:true,published:true,sortOrder:6}
];
async function main(){await connectToDatabase();for(const item of projects){await Project.findOneAndUpdate({$or:[{slug:item.slug},{title:item.title}]},{$set:item},{upsert:true,returnDocument:"after",setDefaultsOnInsert:true})}console.log(`Seeded or updated ${projects.length} projects without deleting existing records.`);process.exit(0)}
main().catch(error=>{console.error(error instanceof Error?error.message:"Project seed failed");process.exit(1)});
